{
  "_from": "axios-error@^0.7.18",
  "_id": "axios-error@0.7.18",
  "_inBundle": false,
  "_integrity": "sha512-96qeJNpA9yBtWvWI3mTZzDAGow0VNw/FlWnMMNDP2GQizyKVEbHPA4JwBZ365rm1uGTFtU4F+uAI7TWxlZ/NoQ==",
  "_location": "/axios-error",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "axios-error@^0.7.18",
    "name": "axios-error",
    "escapedName": "axios-error",
    "rawSpec": "^0.7.18",
    "saveSpec": null,
    "fetchSpec": "^0.7.18"
  },
  "_requiredBy": [
    "/messaging-api-line",
    "/messaging-api-messenger",
    "/messaging-api-slack",
    "/messaging-api-telegram",
    "/messaging-api-viber"
  ],
  "_resolved": "https://registry.npmjs.org/axios-error/-/axios-error-0.7.18.tgz",
  "_shasum": "9d5fd6942b5ecd7f162b700b58a4c981c704859c",
  "_spec": "axios-error@^0.7.18",
  "_where": "/Users/cookiie/Chatbot/node_modules/messaging-api-line",
  "bugs": {
    "url": "https://github.com/Yoctol/messaging-apis/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "An axios error wrapper that aim to provide clear error message to the user",
  "devDependencies": {
    "axios": "^0.19.0",
    "axios-mock-adapter": "^1.15.0"
  },
  "engines": {
    "node": ">=6"
  },
  "gitHead": "4318450a056e285e70093a80fc0bf79910665642",
  "homepage": "https://github.com/Yoctol/messaging-apis#readme",
  "keywords": [
    "axios",
    "error",
    "http"
  ],
  "license": "MIT",
  "main": "lib/index.js",
  "name": "axios-error",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Yoctol/messaging-apis.git"
  },
  "version": "0.7.18"
}
